#Docker commands
# docker compose up -d --build
# docker compose up -d --build --force-recreate
# docker exec -it toolchain bash

services:
  toolchain:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: toolchain
    env_file:
      - .env
    volumes:
      - ./:/home/dev/workspace
      - ./sysroots:/home/dev/sysroots
    restart: unless-stopped
    tty: true
    stdin_open: true
    privileged: true
    entrypoint: ["/home/dev/workspace/entrypoint.sh"]